# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: lab07

on:
  push:
    paths:
      - 'lab07/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'lab07/go.mod'
        cache: false

    - name: Run
      working-directory: 'lab07'
      run: go test