# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: lab06

on:
  push:
    paths:
      - 'lab06/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'lab06/go.mod'
        cache: false

    - name: Build
      working-directory: 'lab06'
      run: |
        pip install -r requirements.txt
        cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .
        GOOS=js GOARCH=wasm go build -o wasm/lib.wasm wasm/main.go

    - name: Run
      working-directory: 'lab06'
      run: |
        go run server.go &
        python3 validate.py
